dist: xenial
language: python
env:
  - BACKEND_DIR='backend/src' FRONTEND_DIR='web/app'

python:
  - "3.7"

addons:
  sonarcloud:
    organization: "borisv13-github" # the key of the org you chose at step #3
    token:
      secure: $SONAR_TOKEN # encrypted value of your token

install:
  - pip install -r $BACKEND_DIR/main/requirements.txt
  - pip install -r $BACKEND_DIR/test/requirements.txt
  - npm --prefix $FRONTEND_DIR install

before_script:
  - pylint $BACKEND_DIR/

script:
  - pytest --cov-report term --cov=.
  - coverage xml
  - sonar-scanner

after_script:
  - codecov

# safelist
branches:
  only:
    - master
